# config/config.yaml

seed: 1234

log_dir: outputs

model:
  file_dir: ???
  model_name: pytorch_model.bin
  config_name: config.json
  output_dir: null
  private:
    num_hidden_layers: 1

train:
  epoch: 10
  early_stop: 10
  batch_size: 16
  warmup_steps: 0.0
  gradient_accumulation_steps: 1
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  class_weight_scheme: no_weight
  focal_loss_gamma: 2 # If use balanced_focal
  balanced_loss_beta: 0.999999 # If use balanced_focal

distillation:
  method: average
  systems: null

aekd:
  C: 0.6
  nu: null # Store during execution
  svm_norm: false

eval:
  batch_size: 32

optim:
  lr: 5e-5
  adam_B1: 0.9
  adam_B2: 0.999
  adam_eps: 1e-8
  weight_decay: 0

data:
  train_dir: ???
  system_results_dir: ???
  ignore_train_pageids: false
  contain_all_train_pageids: true
  max_sample_size: 1000
  dev_rate: 0.1
  seq_len: 512
  duplicate: 100
  debug: false
  num_workers: 8
  shuffle: true

device:
  fp16: true
  fp16_opt_level: O1
  no_cuda: false
  device: null # Store during execution
  n_gpu: null # Store during execution
